version: "{build}"

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
  - npm install jest --global

cache:
  - '%LOCALAPPDATA%/Yarn'

test_script:
  - node --version
  - npm --version
  - jest

# Don't actually build.
build: off